### ISSUE TITLE
if lines[i].find("%") != -1:

### ISSUE THREAD

**Issue by bhamadicharef** [akleemans/latex-wordcount#1]
python3 wordcount.py KML_ver06.6.tex
Traceback (most recent call last):
  File "wordcount.py", line 40, in <module>
    if lines[i].find("%") != -1:
TypeError: argument should be integer or bytes-like object, not 'str'

**Comment by preminstrel** [comment]
same problem

**Comment by akleemans** [comment]
@bhamadicharef @preminstrel Thanks, will look into it!

**Comment by akleemans** [comment]
@bhamadicharef @preminstrel Fixed in 3037fc5d4265d09c4a831ae487cc705729a931c0, successfully tested with Python 3.11. Can you check if it works for you?
